// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// type_works
bool type_works(std::string x);
RcppExport SEXP wicket_type_works(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(type_works(x));
    return rcpp_result_gen;
END_RCPP
}
// lint_point
DataFrame lint_point(CharacterVector x);
RcppExport SEXP wicket_lint_point(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(lint_point(x));
    return rcpp_result_gen;
END_RCPP
}
// validate_wkt
DataFrame validate_wkt(CharacterVector wkt);
RcppExport SEXP wicket_validate_wkt(SEXP wktSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type wkt(wktSEXP);
    rcpp_result_gen = Rcpp::wrap(validate_wkt(wkt));
    return rcpp_result_gen;
END_RCPP
}
