# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lint_wkt <- function(wkt) {
    .Call('wicket_lint_wkt', PACKAGE = 'wicket', wkt)
}

